'use strict';

exports.categories = [
  {"category_id": 8209, "title": "Accountants"},
  {"category_id": 8211, "title": "Administration and bookkeeping offices"},
  {"category_id": 8212, "title": "Adventure sports"},
  {"category_id": 8631, "title": "Advertising"},
  {"category_id": 8219, "title": "Agencies and commission traders"},
  {"category_id": 8221, "title": "Agricultural machines"},
  {"category_id": 8511, "title": "Agriculture and horticulture"},
  {"category_id": 8222, "title": "Airconditioning"},
  {"category_id": 8775, "title": "Aircraft company"},
  {"category_id": 8530, "title": "Airlines"},
  {"category_id": 54885, "title": "Airport access"},
  {"category_id": 8529, "title": "Airports and airfields"},
  {"category_id": 8225, "title": "Alternative healers"},
  {"category_id": 8819, "title": "Ambulances and disabled transport"},
  {"category_id": 8229, "title": "Amusement centres"},
  {"category_id": 54465, "title": "Amusement parks"},
  {"category_id": 8342, "title": "Animal feed companies"},
  {"category_id": 8338, "title": "Animal rescue and animal services"},
  {"category_id": 17422, "title": "Antiques and art"},
  {"category_id": 8793, "title": "Aquatic sports"},
  {"category_id": 8234, "title": "Architects"},
  {"category_id": 8233, "title": "Archives and documentation centres"},
  {"category_id": 8383, "title": "Art galleries"},
  {"category_id": 8499, "title": "Artists"},
  {"category_id": 8235, "title": "Artists and entertainment companies"},
  {"category_id": 8503, "title": "Arts and crafts"},
  {"category_id": 8237, "title": "Astrologists"},
  {"category_id": 56134, "title": "Auctions"},
  {"category_id": 8238, "title": "Audiovisual equipment"},
  {"category_id": 8244, "title": "Automation"},
  {"category_id": 8823, "title": "Awnings and insect screens"},
  {"category_id": 8316, "title": "Baby and toddler health centres"},
  {"category_id": 8247, "title": "Baby products"},
  {"category_id": 8333, "title": "Bailiffs"},
  {"category_id": 8249, "title": "Bakeries"},
  {"category_id": 8250, "title": "Balloon flights"},
  {"category_id": 8252, "title": "Banks"},
  {"category_id": 8210, "title": "Batteries"},
  {"category_id": 8253, "title": "Beauty centres and saunas"},
  {"category_id": 8662, "title": "Beauty salons"},
  {"category_id": 24658, "title": "Bed and breakfast"},
  {"category_id": 8254, "title": "Beds and mattresses"},
  {"category_id": 8440, "title": "Bee-keepers"},
  {"category_id": 8224, "title": "Beverages"},
  {"category_id": 8370, "title": "Bicycle parking"},
  {"category_id": 8369, "title": "Bicycles and scooters"},
  {"category_id": 8681, "title": "Blacksmiths and forgers"},
  {"category_id": 8604, "title": "Boarding houses"},
  {"category_id": 8452, "title": "Boarding schools"},
  {"category_id": 8280, "title": "Boats"},
  {"category_id": 8275, "title": "Book binders"},
  {"category_id": 8276, "title": "Bookshops"},
  {"category_id": 54892, "title": "Border crossing"},
  {"category_id": 8474, "title": "Bowling and skittle alleys"},
  {"category_id": 8375, "title": "Breeding companies"},
  {"category_id": 8269, "title": "Breweries"},
  {"category_id": 8702, "title": "Bricks"},
  {"category_id": 8290, "title": "Bridal shops"},
  {"category_id": 8289, "title": "Bridge construction"},
  {"category_id": 8580, "title": "Broadcasting companies"},
  {"category_id": 8278, "title": "Brushes and paintbrushes"},
  {"category_id": 8206, "title": "Building contractors"},
  {"category_id": 8282, "title": "Building materials and machines"},
  {"category_id": 8283, "title": "Building site equipment"},
  {"category_id": 56083, "title": "Business centres"},
  {"category_id": 8638, "title": "Business gifts"},
  {"category_id": 8811, "title": "Business services"},
  {"category_id": 8676, "title": "Butcher shops"},
  {"category_id": 8463, "title": "Cable companies"},
  {"category_id": 8294, "title": "Call centres"},
  {"category_id": 8295, "title": "Campers caravans and folding campers"},
  {"category_id": 8296, "title": "Camping grounds and campsites"},
  {"category_id": 8466, "title": "Camping supplies"},
  {"category_id": 8240, "title": "Car accessories and car parts"},
  {"category_id": 8297, "title": "Car body works and coach building"},
  {"category_id": 8242, "title": "Car breakdown services"},
  {"category_id": 15029, "title": "Car leasing"},
  {"category_id": 8384, "title": "Car maintenance garages"},
  {"category_id": 8239, "title": "Car modifications"},
  {"category_id": 51160, "title": "Car rental"},
  {"category_id": 8245, "title": "Car repair services"},
  {"category_id": 8241, "title": "Car traders"},
  {"category_id": 17497, "title": "Car washes"},
  {"category_id": 8246, "title": "Car wreckers"},
  {"category_id": 1423, "title": "Care centres"},
  {"category_id": 22526, "title": "Care products"},
  {"category_id": 8528, "title": "Career guidance"},
  {"category_id": 8739, "title": "Carpentry"},
  {"category_id": 21599, "title": "Cash machines"},
  {"category_id": 8298, "title": "Casinos"},
  {"category_id": 8299, "title": "Catering and party services"},
  {"category_id": 8300, "title": "CDs DVDs and records"},
  {"category_id": 8609, "title": "Ceilings"},
  {"category_id": 8266, "title": "Cement and concrete"},
  {"category_id": 8258, "title": "Cemeteries"},
  {"category_id": 8302, "title": "Central heating"},
  {"category_id": 8303, "title": "Certifications and quality marks"},
  {"category_id": 8464, "title": "Chambers of commerce"},
  {"category_id": 8304, "title": "Charitable institutions"},
  {"category_id": 8305, "title": "Chauffeur services"},
  {"category_id": 8306, "title": "Chemical industry"},
  {"category_id": 8307, "title": "Chemical products"},
  {"category_id": 8480, "title": "Child care"},
  {"category_id": 8479, "title": "Children's activities"},
  {"category_id": 8666, "title": "Chimney sweeps"},
  {"category_id": 8612, "title": "Chiropodists"},
  {"category_id": 8675, "title": "Cigars, cigarettes and tobacco"},
  {"category_id": 8271, "title": "Cinemas"},
  {"category_id": 56069, "title": "City centre"},
  {"category_id": 8577, "title": "Civil-law notaries and notary offices"},
  {"category_id": 8665, "title": "Cleaners and cleaning services"},
  {"category_id": 8663, "title": "Cleaning equipment"},
  {"category_id": 8664, "title": "Cleaning products"},
  {"category_id": 8484, "title": "Clinics"},
  {"category_id": 8481, "title": "Clothing"},
  {"category_id": 8482, "title": "Clothing accessories"},
  {"category_id": 8740, "title": "Coaches and touring cars"},
  {"category_id": 8490, "title": "Coffee and tea"},
  {"category_id": 17754, "title": "Coffee shops"},
  {"category_id": 8491, "title": "Coffeebars and tea shops"},
  {"category_id": 8718, "title": "Cog wheels"},
  {"category_id": 8483, "title": "Colour consultants"},
  {"category_id": 8771, "title": "Commercial fishing"},
  {"category_id": 8256, "title": "Commercial interiors"},
  {"category_id": 8309, "title": "Commercial photographers"},
  {"category_id": 8310, "title": "Compressors"},
  {"category_id": 8312, "title": "Computers and peripherals"},
  {"category_id": 8308, "title": "Confectioners"},
  {"category_id": 8313, "title": "Conferences and conventions"},
  {"category_id": 8314, "title": "Conflict mediation"},
  {"category_id": 8368, "title": "Congratulatory services"},
  {"category_id": 8213, "title": "Consultancy firms"},
  {"category_id": 8317, "title": "Consumer information"},
  {"category_id": 8319, "title": "Containers"},
  {"category_id": 8527, "title": "Contracting firms"},
  {"category_id": 14866, "title": "Cooking studios"},
  {"category_id": 8487, "title": "Cooling technology"},
  {"category_id": 8320, "title": "Copy shops and reproductions"},
  {"category_id": 8729, "title": "Copywriters"},
  {"category_id": 8321, "title": "Cosmetic supplies"},
  {"category_id": 8322, "title": "Cosmetic surgery"},
  {"category_id": 8488, "title": "Courier deliveries"},
  {"category_id": 8836, "title": "Court houses"},
  {"category_id": 8494, "title": "Crane trucks and breakdown trucks"},
  {"category_id": 54879, "title": "Cultural centre"},
  {"category_id": 8804, "title": "Currency exchange and money transfers"},
  {"category_id": 8825, "title": "Dairy products"},
  {"category_id": 8777, "title": "Damp proofing and control"},
  {"category_id": 8326, "title": "Dancing schools"},
  {"category_id": 8328, "title": "Data communication"},
  {"category_id": 8327, "title": "Databanks and data enhancement"},
  {"category_id": 8329, "title": "Dating services"},
  {"category_id": 8442, "title": "Debt-collection agencies"},
  {"category_id": 8331, "title": "Delicatessen"},
  {"category_id": 8680, "title": "Demolition work"},
  {"category_id": 56119, "title": "Dental mechanics"},
  {"category_id": 8715, "title": "Dentists"},
  {"category_id": 8787, "title": "Department stores"},
  {"category_id": 8334, "title": "Diamonds"},
  {"category_id": 8343, "title": "Dieticians"},
  {"category_id": 8345, "title": "Discotheques and nightclubs"},
  {"category_id": 8350, "title": "Distribution of printed matter"},
  {"category_id": 8346, "title": "Distributors and forwarding agents"},
  {"category_id": 8792, "title": "District water boards"},
  {"category_id": 8281, "title": "DIY stores"},
  {"category_id": 8423, "title": "Dog and cat grooming salons"},
  {"category_id": 8424, "title": "Dog schools"},
  {"category_id": 8332, "title": "Doors"},
  {"category_id": 8248, "title": "Dredging works"},
  {"category_id": 8204, "title": "Drives and controls"},
  {"category_id": 8347, "title": "Drugstore supplies"},
  {"category_id": 8411, "title": "Earthworks"},
  {"category_id": 50697, "title": "Education and courses"},
  {"category_id": 8581, "title": "Educational material"},
  {"category_id": 56197, "title": "Electric vehicle charging points"},
  {"category_id": 8629, "title": "Electrical appliances"},
  {"category_id": 8354, "title": "Electricians"},
  {"category_id": 8215, "title": "Electronic payment systems"},
  {"category_id": 8356, "title": "Electrotechnical items"},
  {"category_id": 8227, "title": "Embassies and consulates"},
  {"category_id": 8293, "title": "Emergency services"},
  {"category_id": 8357, "title": "Emigration agencies"},
  {"category_id": 8232, "title": "Employment intermediation"},
  {"category_id": 8564, "title": "Engine overhaul and placement"},
  {"category_id": 8444, "title": "Engineering companies"},
  {"category_id": 8406, "title": "Engravers"},
  {"category_id": 8554, "title": "Environmental services"},
  {"category_id": 8649, "title": "Equestrian sports equipment"},
  {"category_id": 8360, "title": "Escort services"},
  {"category_id": 8364, "title": "Events and exhibition management"},
  {"category_id": 8363, "title": "Events and exhibitions"},
  {"category_id": 22458, "title": "Eviction service companies"},
  {"category_id": 8218, "title": "Exhaust systems"},
  {"category_id": 8365, "title": "Facility services"},
  {"category_id": 8800, "title": "Fair trade shops"},
  {"category_id": 8830, "title": "Farming"},
  {"category_id": 8420, "title": "Farriers"},
  {"category_id": 8559, "title": "Fashion designers"},
  {"category_id": 8270, "title": "Fashion Jewellery"},
  {"category_id": 8417, "title": "Fences"},
  {"category_id": 8751, "title": "Ferry services"},
  {"category_id": 54891, "title": "Ferry terminal"},
  {"category_id": 8546, "title": "Fertilizers and forage"},
  {"category_id": 8371, "title": "Filters and filter materials"},
  {"category_id": 8373, "title": "Financing"},
  {"category_id": 8286, "title": "Fire brigades"},
  {"category_id": 8783, "title": "Fireworks"},
  {"category_id": 8769, "title": "Fish and fish products"},
  {"category_id": 8374, "title": "Fitness centres"},
  {"category_id": 8772, "title": "Flags banners and bunting"},
  {"category_id": 8776, "title": "Floors"},
  {"category_id": 8273, "title": "Flowers and plants"},
  {"category_id": 8376, "title": "Foils"},
  {"category_id": 8518, "title": "Food suppliers"},
  {"category_id": 8279, "title": "Forestry"},
  {"category_id": 8381, "title": "Foundation engineering"},
  {"category_id": 8377, "title": "Fountains and ponds"},
  {"category_id": 8380, "title": "Franchising"},
  {"category_id": 8336, "title": "Frozen products"},
  {"category_id": 8407, "title": "Fruit and vegetables"},
  {"category_id": 8476, "title": "Fun fair companies"},
  {"category_id": 8747, "title": "Funeral services"},
  {"category_id": 8551, "title": "Furnitures"},
  {"category_id": 56196, "title": "Gambling"},
  {"category_id": 8744, "title": "Garden centres"},
  {"category_id": 8742, "title": "Garden landscaping and maintenance"},
  {"category_id": 8743, "title": "Garden tools and supplies"},
  {"category_id": 8385, "title": "Gas appliances"},
  {"category_id": 8386, "title": "Gasses"},
  {"category_id": 8220, "title": "Generators and electromotors"},
  {"category_id": 8394, "title": "Gifts"},
  {"category_id": 8400, "title": "Glass"},
  {"category_id": 8399, "title": "Glasswork porcelain and earthenware"},
  {"category_id": 8521, "title": "Glue and gluing equipment"},
  {"category_id": 8402, "title": "Golf courses"},
  {"category_id": 8556, "title": "Government and ministeries"},
  {"category_id": 8403, "title": "Graphic companies"},
  {"category_id": 8473, "title": "Greenhouse construction"},
  {"category_id": 8408, "title": "Group accommodations"},
  {"category_id": 8507, "title": "Growers"},
  {"category_id": 17751, "title": "Growshops"},
  {"category_id": 8413, "title": "Hair pieces and wigs"},
  {"category_id": 8471, "title": "Hairdressers"},
  {"category_id": 48801, "title": "Hairdressers supplies"},
  {"category_id": 8812, "title": "Hall rental"},
  {"category_id": 8486, "title": "Handyman businesses"},
  {"category_id": 8415, "title": "Harbours"},
  {"category_id": 8439, "title": "Hardware shops"},
  {"category_id": 8396, "title": "Health care centres"},
  {"category_id": 8397, "title": "Health services"},
  {"category_id": 8425, "title": "Hearing aids"},
  {"category_id": 8418, "title": "Helicopters"},
  {"category_id": 8419, "title": "Hobby supplies"},
  {"category_id": 8421, "title": "Holdings"},
  {"category_id": 8749, "title": "Holiday accommodations"},
  {"category_id": 8737, "title": "Home care"},
  {"category_id": 22414, "title": "Home decoration"},
  {"category_id": 8593, "title": "Horses"},
  {"category_id": 8426, "title": "Hospitality industry supplies"},
  {"category_id": 8818, "title": "Hospitals"},
  {"category_id": 8428, "title": "Hotels"},
  {"category_id": 8434, "title": "Household articles"},
  {"category_id": 8806, "title": "Housing associations"},
  {"category_id": 8832, "title": "Hunting"},
  {"category_id": 8435, "title": "Hydraulic equipment"},
  {"category_id": 8790, "title": "Hydraulic-engineering works"},
  {"category_id": 8318, "title": "Ice cream"},
  {"category_id": 8437, "title": "Ice skating rinks"},
  {"category_id": 17752, "title": "Ice-cream parlours"},
  {"category_id": 15827, "title": "Industrial automation"},
  {"category_id": 23564, "title": "Industrial design agencies"},
  {"category_id": 8477, "title": "Industrial kettles"},
  {"category_id": 8731, "title": "Information telephone lines"},
  {"category_id": 8838, "title": "Information websites"},
  {"category_id": 15823, "title": "Installation materials"},
  {"category_id": 8446, "title": "Installers"},
  {"category_id": 8456, "title": "Insulation"},
  {"category_id": 8766, "title": "Insurance"},
  {"category_id": 8449, "title": "Interior builders"},
  {"category_id": 8450, "title": "Interior designers"},
  {"category_id": 8753, "title": "Internal combustion engines"},
  {"category_id": 8451, "title": "Internal transport"},
  {"category_id": 8454, "title": "Internet services"},
  {"category_id": 8455, "title": "Investment companies"},
  {"category_id": 8261, "title": "Investments"},
  {"category_id": 8461, "title": "Jewellers"},
  {"category_id": 8459, "title": "Journalists and press agencies"},
  {"category_id": 8472, "title": "Karting and racing"},
  {"category_id": 8677, "title": "Keys and locks"},
  {"category_id": 8478, "title": "Kitchens"},
  {"category_id": 8508, "title": "Laboratories"},
  {"category_id": 8509, "title": "Laboratory necessities"},
  {"category_id": 8510, "title": "Ladders and scaffolding"},
  {"category_id": 54882, "title": "Landmark"},
  {"category_id": 8515, "title": "Lasers and laser technology"},
  {"category_id": 8834, "title": "Laundry services , launderettes and dry cleaners"},
  {"category_id": 8214, "title": "Lawyers"},
  {"category_id": 8630, "title": "Legal aid"},
  {"category_id": 8268, "title": "Libraries and reading rooms"},
  {"category_id": 8416, "title": "Lifting and hoisting devices"},
  {"category_id": 8520, "title": "Lifts and lift parts"},
  {"category_id": 8391, "title": "Lighting and sound equipment"},
  {"category_id": 8759, "title": "Lights and lighting"},
  {"category_id": 8523, "title": "Lingerie"},
  {"category_id": 8679, "title": "Liquor stores-"},
  {"category_id": 8757, "title": "Living accommodation rental"},
  {"category_id": 8682, "title": "Lubricants"},
  {"category_id": 8516, "title": "Luggage bags and leatherware"},
  {"category_id": 8532, "title": "Machines"},
  {"category_id": 8517, "title": "Magazine folder rental"},
  {"category_id": 8534, "title": "Magnets"},
  {"category_id": 8770, "title": "Make up art"},
  {"category_id": 8513, "title": "Maps and streetmaps"},
  {"category_id": 8457, "title": "Marinas and wharfs"},
  {"category_id": 8538, "title": "Marketing agencies"},
  {"category_id": 56033, "title": "Markets"},
  {"category_id": 8550, "title": "Masonry"},
  {"category_id": 8541, "title": "Masseurs"},
  {"category_id": 8493, "title": "Maternity care"},
  {"category_id": 8773, "title": "Meat products"},
  {"category_id": 17447, "title": "Media"},
  {"category_id": 8542, "title": "Medical equipment and instruments"},
  {"category_id": 8543, "title": "Medical examinations"},
  {"category_id": 8236, "title": "Medical practitioners and specialists"},
  {"category_id": 8387, "title": "Mental health care"},
  {"category_id": 8548, "title": "Metal refinement"},
  {"category_id": 8549, "title": "Metalware"},
  {"category_id": 8547, "title": "Metalworking"},
  {"category_id": 8797, "title": "Meteorological services"},
  {"category_id": 8287, "title": "Microcars"},
  {"category_id": 8760, "title": "Midwives"},
  {"category_id": 55927, "title": "Mineral extraction"},
  {"category_id": 8553, "title": "Miniature golf"},
  {"category_id": 8558, "title": "Modelling agencies"},
  {"category_id": 8537, "title": "Models and miniatures"},
  {"category_id": 8714, "title": "Modular construction"},
  {"category_id": 8436, "title": "Mortgages"},
  {"category_id": 8562, "title": "Motorcycles and motorcycle accessories"},
  {"category_id": 8536, "title": "Moulds and stencils"},
  {"category_id": 56042, "title": "Mountain  pass"},
  {"category_id": 8756, "title": "Moving Services"},
  {"category_id": 8565, "title": "Museums"},
  {"category_id": 8567, "title": "Music schools and lessons"},
  {"category_id": 54876, "title": "Music venues"},
  {"category_id": 8566, "title": "Musical instruments and sheet music"},
  {"category_id": 8571, "title": "Nail studios"},
  {"category_id": 54883, "title": "Natural attraction"},
  {"category_id": 8573, "title": "Natural stone"},
  {"category_id": 8572, "title": "Nature and environment organisations"},
  {"category_id": 8575, "title": "New age shops and services"},
  {"category_id": 56195, "title": "Nightclubs"},
  {"category_id": 8764, "title": "Nurses"},
  {"category_id": 8467, "title": "Office furniture and professional furniture"},
  {"category_id": 8469, "title": "Office supplies and office equipment"},
  {"category_id": 8590, "title": "Optical instruments"},
  {"category_id": 8589, "title": "Opticians"},
  {"category_id": 8561, "title": "Oral hygienists"},
  {"category_id": 8574, "title": "Organic foods and natural products"},
  {"category_id": 50279, "title": "Orthodontists"},
  {"category_id": 8762, "title": "Packaging"},
  {"category_id": 8755, "title": "Paint and lacquer"},
  {"category_id": 8659, "title": "Painter decorators"},
  {"category_id": 8594, "title": "Pallets"},
  {"category_id": 8595, "title": "Paper and paperware"},
  {"category_id": 8596, "title": "Parking"},
  {"category_id": 8833, "title": "Parks and gardens"},
  {"category_id": 17753, "title": "Party centres"},
  {"category_id": 8367, "title": "Party items"},
  {"category_id": 54887, "title": "Passenger transport ticket office"},
  {"category_id": 8579, "title": "Patent and brand offices"},
  {"category_id": 8265, "title": "Paving"},
  {"category_id": 8600, "title": "Pedicure"},
  {"category_id": 8831, "title": "Personal protection products"},
  {"category_id": 8583, "title": "Pest control"},
  {"category_id": 8340, "title": "Pet shops"},
  {"category_id": 8720, "title": "Petrol stations"},
  {"category_id": 56000, "title": "Petting zoo"},
  {"category_id": 8366, "title": "Pharmaceuticals"},
  {"category_id": 8231, "title": "Pharmacies"},
  {"category_id": 8378, "title": "Photographic laboratories"},
  {"category_id": 8379, "title": "Photography shops"},
  {"category_id": 8382, "title": "Physical therapists"},
  {"category_id": 8606, "title": "Pipelines"},
  {"category_id": 54884, "title": "Place of worship"},
  {"category_id": 8710, "title": "Plasterers"},
  {"category_id": 8505, "title": "Plastics"},
  {"category_id": 8691, "title": "Playground equipment and street furniture"},
  {"category_id": 8692, "title": "Playgrounds"},
  {"category_id": 8525, "title": "Plumbers"},
  {"category_id": 8613, "title": "Podotherapists"},
  {"category_id": 8779, "title": "Pointing"},
  {"category_id": 8616, "title": "Police and law enforcement"},
  {"category_id": 8618, "title": "Post offices"},
  {"category_id": 8620, "title": "Postage stamps, coins, medals"},
  {"category_id": 8614, "title": "Poulterers"},
  {"category_id": 8352, "title": "Precious metals and semiprecious stones"},
  {"category_id": 8826, "title": "Pregnancy guidance"},
  {"category_id": 8348, "title": "Printing companies"},
  {"category_id": 8839, "title": "Prisons"},
  {"category_id": 8544, "title": "Process control technology"},
  {"category_id": 8264, "title": "Professional organizations"},
  {"category_id": 8624, "title": "Project development"},
  {"category_id": 8623, "title": "Project furnishing"},
  {"category_id": 8259, "title": "Property management"},
  {"category_id": 8625, "title": "Psychologists"},
  {"category_id": 54881, "title": "Public amenities"},
  {"category_id": 8828, "title": "Public swimming pools and swimming schools"},
  {"category_id": 54886, "title": "Public transport stop"},
  {"category_id": 8587, "title": "Public transportation"},
  {"category_id": 8746, "title": "Publishers"},
  {"category_id": 8291, "title": "Pubs and bars"},
  {"category_id": 8617, "title": "Pumps"},
  {"category_id": 8445, "title": "Purchasing groups"},
  {"category_id": 8535, "title": "Real-estate agencies"},
  {"category_id": 8837, "title": "Recreation parks"},
  {"category_id": 54893, "title": "Recreational areas"},
  {"category_id": 8699, "title": "Recreational fishing"},
  {"category_id": 8632, "title": "Recycling"},
  {"category_id": 8643, "title": "Reed and rush"},
  {"category_id": 8635, "title": "Reintegration offices"},
  {"category_id": 51063, "title": "Religious organisations"},
  {"category_id": 52004, "title": "Remedial therapists"},
  {"category_id": 8598, "title": "Remnants lots"},
  {"category_id": 8633, "title": "Rescue companies"},
  {"category_id": 8582, "title": "Research bureaus"},
  {"category_id": 8727, "title": "Residential centres"},
  {"category_id": 54889, "title": "Rest area"},
  {"category_id": 56076, "title": "Restaurant area"},
  {"category_id": 8640, "title": "Restaurants"},
  {"category_id": 8641, "title": "Restoration"},
  {"category_id": 8602, "title": "Retirement Pensions"},
  {"category_id": 21303, "title": "Riding schools"},
  {"category_id": 8798, "title": "Road construction"},
  {"category_id": 8325, "title": "Roofers"},
  {"category_id": 8835, "title": "Ropework and netting"},
  {"category_id": 8647, "title": "Rubber products"},
  {"category_id": 8284, "title": "Safes"},
  {"category_id": 8752, "title": "Safety and prevention"},
  {"category_id": 8814, "title": "Sailmakers"},
  {"category_id": 8813, "title": "Sand and gravel"},
  {"category_id": 8288, "title": "Sandwich shops"},
  {"category_id": 8650, "title": "Sanitary fixtures"},
  {"category_id": 8810, "title": "Sawmills"},
  {"category_id": 8745, "title": "Second hand goods"},
  {"category_id": 8468, "title": "Secretarial services"},
  {"category_id": 8267, "title": "Security"},
  {"category_id": 8644, "title": "Sewage systems"},
  {"category_id": 8568, "title": "Sewing and needlework supplies"},
  {"category_id": 8671, "title": "Sex clubs and sex saunas"},
  {"category_id": 8672, "title": "Sex shops"},
  {"category_id": 8678, "title": "Sharpening and polishing"},
  {"category_id": 8608, "title": "Sheet-metal work"},
  {"category_id": 8687, "title": "Sheltered employment"},
  {"category_id": 8652, "title": "Shipbuilding and ship repair"},
  {"category_id": 8634, "title": "Shipowning companies and sightseeing cruises"},
  {"category_id": 56030, "title": "Shipping industry"},
  {"category_id": 8660, "title": "Shoes and footwear"},
  {"category_id": 21600, "title": "Shopping centres"},
  {"category_id": 54878, "title": "Shopping service"},
  {"category_id": 8208, "title": "Slaughterhouses"},
  {"category_id": 17750, "title": "Smart shops"},
  {"category_id": 8683, "title": "Snackbars"},
  {"category_id": 8686, "title": "Social insurance"},
  {"category_id": 8685, "title": "Social services"},
  {"category_id": 8684, "title": "Social work"},
  {"category_id": 8492, "title": "Socks and stockings"},
  {"category_id": 8807, "title": "Soft furnishings"},
  {"category_id": 8688, "title": "Software"},
  {"category_id": 8274, "title": "Soil analysis"},
  {"category_id": 8409, "title": "Soil drilling and well point drainage"},
  {"category_id": 8689, "title": "Souvenirs"},
  {"category_id": 8524, "title": "Speech therapists"},
  {"category_id": 8694, "title": "Sports centres and sports fields"},
  {"category_id": 8693, "title": "Sports goods"},
  {"category_id": 8696, "title": "Sports organisations"},
  {"category_id": 8697, "title": "Sports prizes"},
  {"category_id": 8698, "title": "Sports schools and clubs"},
  {"category_id": 56023, "title": "Stadiums"},
  {"category_id": 8701, "title": "Stage builders and stand builders"},
  {"category_id": 8741, "title": "Stairs"},
  {"category_id": 8668, "title": "Stationery"},
  {"category_id": 8700, "title": "Steel construction companies"},
  {"category_id": 8353, "title": "Stock brokerage"},
  {"category_id": 54875, "title": "Stock exchanges"},
  {"category_id": 8588, "title": "Storage and transshipment"},
  {"category_id": 8719, "title": "Storage tanks"},
  {"category_id": 8412, "title": "Stoves and heaters"},
  {"category_id": 8709, "title": "Studios and productions"},
  {"category_id": 8711, "title": "Stylists"},
  {"category_id": 8673, "title": "Sun rooms and verandas"},
  {"category_id": 8821, "title": "Sunbeds and tanning booths"},
  {"category_id": 8713, "title": "Supermarkets"},
  {"category_id": 8820, "title": "Sweets"},
  {"category_id": 8827, "title": "Swimming pools and whirlpools"},
  {"category_id": 8722, "title": "Tattoos and body art"},
  {"category_id": 8260, "title": "Tax offices"},
  {"category_id": 8339, "title": "Taxidermists"},
  {"category_id": 8725, "title": "Taxis"},
  {"category_id": 8728, "title": "Technical drawing agencies"},
  {"category_id": 8730, "title": "Telecommunication"},
  {"category_id": 8732, "title": "Telephone shops"},
  {"category_id": 8733, "title": "Textiles"},
  {"category_id": 8735, "title": "Theatres"},
  {"category_id": 8462, "title": "Ticket sales and reservations"},
  {"category_id": 8726, "title": "Tiles"},
  {"category_id": 8429, "title": "Timber board and plywood"},
  {"category_id": 8738, "title": "Time registration systems"},
  {"category_id": 54890, "title": "Toll booth"},
  {"category_id": 8393, "title": "Tools"},
  {"category_id": 8637, "title": "Tour guides"},
  {"category_id": 8784, "title": "Tourist information"},
  {"category_id": 8690, "title": "Toys and games"},
  {"category_id": 8414, "title": "Trade centres"},
  {"category_id": 8750, "title": "Trade unions"},
  {"category_id": 8758, "title": "Traffic schools"},
  {"category_id": 8205, "title": "Trailers"},
  {"category_id": 8765, "title": "Translation companies"},
  {"category_id": 8816, "title": "Transmitting and reception equipment"},
  {"category_id": 8799, "title": "Transport"},
  {"category_id": 8636, "title": "Travel agents"},
  {"category_id": 8277, "title": "Tree maintenance"},
  {"category_id": 8782, "title": "Trucks and vans"},
  {"category_id": 8661, "title": "Tutoring"},
  {"category_id": 8251, "title": "Tyres"},
  {"category_id": 54888, "title": "Underground pedestrian walkway"},
  {"category_id": 8324, "title": "Unemployment and benefits offices"},
  {"category_id": 8552, "title": "Upholsterers"},
  {"category_id": 54877, "title": "Utility companies"},
  {"category_id": 8611, "title": "Vacuum and compression technology"},
  {"category_id": 8724, "title": "Valuations"},
  {"category_id": 8243, "title": "Vending machines and gambling machines"},
  {"category_id": 8337, "title": "Veterinarians and veterinary clinics"},
  {"category_id": 8767, "title": "Video"},
  {"category_id": 8768, "title": "Video and DVD rental shops"},
  {"category_id": 8785, "title": "Wall coverings"},
  {"category_id": 8217, "title": "Waste management"},
  {"category_id": 8427, "title": "Watches and clocks"},
  {"category_id": 8789, "title": "Water treatment"},
  {"category_id": 8786, "title": "Weapons and munition"},
  {"category_id": 8794, "title": "Web design"},
  {"category_id": 8795, "title": "Wedding planners"},
  {"category_id": 8796, "title": "Weighing equipment"},
  {"category_id": 8216, "title": "Weight-loss centers"},
  {"category_id": 8514, "title": "Welders and welding materials"},
  {"category_id": 22459, "title": "Window dressers"},
  {"category_id": 8504, "title": "Windows and frames"},
  {"category_id": 8801, "title": "Wine shops and wine tasting companies"},
  {"category_id": 8430, "title": "Woodworking"},
  {"category_id": 8736, "title": "Work from home jobs"}
];
